# Generated by Django 4.2.7 on 2025-05-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BacktestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("indicator", models.CharField(max_length=50)),
                ("short_window", models.IntegerField()),
                ("long_window", models.IntegerField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("total_return", models.FloatField()),
                ("max_drawdown", models.FloatField()),
                ("sharpe_ratio", models.FloatField()),
                ("equity_curve", models.JSONField()),
                ("trades", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="PriceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("volume", models.FloatField()),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="backtester__timesta_0c3b32_idx"
                    )
                ],
            },
        ),
    ]
