# Generated by Django 4.2.7 on 2025-05-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backtester_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backtestresult",
            name="long_window",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="backtestresult",
            name="max_drawdown",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="backtestresult",
            name="sharpe_ratio",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="backtestresult",
            name="short_window",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="backtestresult",
            name="total_return",
            field=models.FloatField(default=0.0),
        ),
    ]
